### ISSUE TITLE
Developer Day

### ISSUE THREAD

**Issue by jhaynie** [TiForward/discuss#11]
I'd like to propose in the near future a TiForward Developer Day.

The goal would be to try and take a number of these proposals and concepts and get together as a community group and discuss them and try and come up with some plans and approaches to them and a roadmap.  This would be a shared vision for us all.

Since we have such a big community, I'd like to find a fair way to represent interests and have as many people involved as want to be -- but also have something that is productive, yet transparent and open.

I don't yet know how to really do the logistics and I don't have anything specific in mind -- I'm opening this topic up to discuss.

So, I'll throw out a few questions:
1. In the case we have more than 15-20 people who want to attend, how would we organize something that's affordable and productive and decide who "represents" us?  When I mean productive, having a detailed set of conversations in groups of 100 just don't work.  And, the larger the group, the more expensive it tends to be on the programatic side.
2. How long should it be?  The goal I think is to have good and deep discussions (almost hack style) and try and make progress ... but not turn it into a one-way conference.  We can do that as a different type venue (Codestrong, TiConf, etc).  1 day? 2 days?
3. Where should it be?  We have people all over the world. 
4. What are some of the high level topics we'd like to flush out (or at least have some definitive proposals around discussions) before we set a date?
5. What else?

**Comment by Sophrinix** [comment]
I'm very much for this idea. I'm pretty sure though that more than 20 people would want to attend such an event. I'll give the logistics some thought.

**Comment by yuchi** [comment]
This is a great proposal, and coming from you has even more value.

I expect too that given the opportunity a lot of people would be more than happy to partecipate, and therefore we indeed risk the _Eternal September effect_ on the quality of the discussion.

On the other hand I believe that in the next months the group of contributing members of the community will stabilize, and representative roles will emerge naturally. The real issue is how to ‘nominate’ people, a numerical approach on number of messages would be of little (if any) use, and on number of commits would cut members contributing valid ideas.

This of course if the venue is a physical one and not ‘in the cloud’. I’m sensitive to this specific topic as an european, even more as an Italian, given that the most palatable is somewhere in the States.

Also I’d be very happen if everything happened in the open sun. If there’s something we can learn from recent OSS experiments, is that being open would bring value, `iff` we can stay focused in the process.

So, if my vote has any meaning (it hasn’t) it would be for a distributed event.

More than one physical venue each connected through high quality, real time communication.
Timezones get in the way, but it’s solvable by choosing a _continuous event_ style.

To keep discussions flowing in a common direction we could choose a moderator for each local event.

**Comment by jhaynie** [comment]
I like the concept of a "virtual event" -- we just would need to work out the logistics.  Google Hangout, Skype, WebEx all break down pretty quickly in numbers greater than 10 (some less).  

My goal would be full "transparency" (i.e. open notes / minutes, discussions, etc).  I don't want us to create some sort of division between the contributors, committers, community, etc.  I'm just suggesting some sort of balanced / pragmatic approach to how to be productive.

**Comment by iotashan** [comment]
I have a suggestion. Perhaps there could be 2-3 locations, and Appcelerator could lend out a couple video conference systems? Could be a good investment so this could be done on a regular basis, with the "locations" moving around the world a bit. 

Obviously Wisconsin is the clear first choice for such an event ;)

**Comment by mattapperson** [comment]
http://www.spreecast.com/ Might be an option?

I am a big fan of the virtual idea

**Comment by WooD1k** [comment]
https://zoom.us/ one more option

+1 for virtual

**Comment by Sophrinix** [comment]
Zoom.us looks slick.

I've used http://bigbluebutton.org/ or https://github.com/bigbluebutton/bigbluebutton big blue button might be a good option here. It's open source and very flexible. It does require a substantial server (think at least 8 gigs of ram) and a good internet connection, but It worked for a group size ~ 20 people. It also bundles FreeSwitch, so you could even have a phone bridge.

 I think the picking 2-3 locations idea would be great. I'd be happy to either reach out the  Atlanta Titanium group  or go north.

**Comment by yuchi** [comment]
Let’s get some numbers on tools [on this Gist](https://gist.github.com/yuchi/735f35727ac8b118bd67).

Once we have a good comparison there we can talk about feasibility here.
