### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by jhaynie** [TiForward/discuss#12]
One of the biggest challenges we've had in the past year in working through Ti.Next has been some of the non-technical issues around compatibility.

One approach we are considering is a clean parallel approach that doesn't (initially) consider backwards compatibility with the Ti.Current API.  

This would allow us to iterate together much faster and help us define a core engine and new set of core APIs without initially having to worry about how to make it work perfect with the existing APIs.  I'm not suggested we throw out the Titanium API in any way.  However, that has been a real struggle for us in the past year .... how do you maintain the current API and current capabilities while you bring in new and frankly re-thought out approaches that we've learned from.

So here's my question.  Is this a pragmatic approach people would consider?

What if we had two streams?  (1) Ti.Current which we will continue to be very active on and (2) Ti.Next which could be not backwards compatible initially.

Then, once we got Ti.Next stable as a core with a solid 1.0 foundation, we'd layer in (or not, we can decide what makes most sense) either backwards compatible API implementations or shims, etc.

This could free us up to go much faster and "kick the can" on trying to reconcile all the existing APIs, current apps, etc.

**Comment by mattapperson** [comment]
In line with this. One of the things that was initially discussed in the first few "meetings" the core Ti.Forward team had was that there was a desire for Ti to have 2 releases a LTS and a latest / stable. Along with that, the idea was to build out Ti.Forward and then have a pollyfill for Ti.Current. I know @yuchi and @Sophrinix are for that... I forget who/if anyone else said they wanted it... conversations were not well documented at that point...

**Comment by mahlon-gumbs** [comment]
My gut tells me that we should not let backwards compatibility grind things to halt. I understand it is very important, but so is progress. As a small example, I'd point to listview vs tableview. Backwards compatibility had to be sacrificed in that case. I'm not suggesting throwing out the baby with the bath water here, but I'd be fine with breaking what's needed in order to advance the platform. We are developers. We'll complain...then adapt.

**Comment by omorandi** [comment]
Right, 1:1 backward compatibility shouldn't be number one goal of Ti.Next. Providing an optimal balance between flexibility and performance should be, IMHO. For instance, I've always been thinking that one of the strengths of Titanium was the level of abstraction provided by its API: easy to use, good portability (the write-once-adapt-everywhere mantra), without sacrificing performance too much. In other words I'd expect Ti.Next API to sit more or less at the same level of abstraction, with increased performance (e.g. by addressing #3 and other issues), but not necessarily in a totally backward compatible way.

**Comment by TheBrousse** [comment]
Maybe I misunderstood, but wasn't TitaniumKit created for that purpose?

Because having a clean slate approach (although very tempting from an engineering point of view) would slow down adoption of the new version since we would shun out the existing community.

So, while my heart would tend to say yes. My head has to say no.

**Comment by jhaynie** [comment]
TitaniumKit is a cross-platform implementation of the Titanium API and sits on top of HAL.

**Comment by jasonkneen** [comment]
Personally, I'd be fine with working with a complete new TiNext product that had no compatibility with the current API on the basis that:-
1. I'd be able to build Android and iOS minimum - no point if I can't build Android or iOS apps as I can now. Windows is nice - but for me, not essential - Android and iOS is vital.
2. It's possible (and sounds like it would be) to build the helper layers / TitaniumKit on-top and as-I-go, allowing me and other devs to share these resources / layers.

So, just as people are writing CommonJS modules now to do stuff, or Widgets, devs can write JS layers that provided a consistent way to create a TabGroup / ActionBar implementation etc. Just like these modules, anyone can fork, change, create, do PRs etc. It doesn't really matter.

In that way, it's possible that the community could end up building the TitaniumKit side of things themselves.

If it was a choice of seeing it delayed because of compatibility with existing code or getting our hands on the ability to starting writing for iOS/Android/Windows now and building these layers together, I'd go with the latter.

**Comment by jasonkneen** [comment]
For example, I was playing with some Swift code in a playground last year. I was "attempting" to see if I could create a bridge between Ti code and Swift to allow me to transition to Swift to build simple apps. 

Purely fun stuff.

https://mobile.twitter.com/jasonkneen/status/503516641851084800

So this in Swift:

`Ti.UI.createLabel(width: 120, height: 40, text: "hello", borderRadius:5, backgroundColor:0xCCCCCC)`

It's not perfect, it's not "Titanium" but it worked. I can see this kind of approach working with people building their own implementations we can chose from or re-write / customise.

In the simplest sense, especially with the UI, we're told everything based on a view e.g Labels, Buttons, Views etc. So someone implementing a based "Ti.Ui.View" class/object could form the basis of everything else.

**Comment by mattapperson** [comment]
@jasonkneen I think a Ti like cross platform layer is needed. That is what makes Ti Ti... bu it should be modular ala nodejs and t I think that compatibility to Ti current should be a polyfill built and worried about AFTER we get Ti.Next out the door.

**Comment by jasonkneen** [comment]
agreed. I'm talking more about the current version yep

**Comment by jasonkneen** [comment]
I'd rather have TiNext sooner and have to start over than wait for backward compatibility

**Comment by mattapperson** [comment]
This seems very unanimous so far...

**Comment by jasonkneen** [comment]
But if the UI building side is based on Ti Classic style, I will probably kill someone.

**Comment by mattapperson** [comment]
@jasonkneen you mean vs alloy?

**Comment by jasonkneen** [comment]
I mean I just don't want to go back to the old way of building UIs with classic, i.e. creating elements, creating views, adding to views, adding views to windows - tedious.

I like the separation with Alloy and ease of creating views with XML / TSS etc - JSON would work also - just I guess something that easily shows the relationships between UI elements rather than messy code that does it manually.

**Comment by mattapperson** [comment]
@jasonkneen While I do not disagree here, and think that some way of defining UI in markup is good (I am a fan of JSX personally, but Alloy has some perks over that at times) We do I think need a programatic API. I feel strongly that both are needed. What is nice about JSX is that the JSX has a 1 to 1 mapping to the markup so devs can choose / use the right tool at the right time.

**Comment by jasonkneen** [comment]
yep not saying one or other. both is good but the big benefit of alloy is rapid ui creation without touching JS code. so s programmatic API that could have that built into would be awesome.

**Comment by mattapperson** [comment]
@jasonkneen having used react for a little while now... I love the fact that there is no template language really... just JS and XML representation of JS.
I think this part of the topic prob needs its own discussion though as we are getting off topic

**Comment by jasonkneen** [comment]
ok

**Comment by yozef** [comment]
+1 I think we shouldn't let backward compatibility slow Ti.Next. 

iOS _(especially)_ & Android are rapidly changing, we should look forward rather than making sure things are backward compatible. I do get updates to older Apps, like everything else, I try to bring them up to date, that's a task developers have to do anyways, and probably may require more time bringing those apps up to date with Ti.Next; However, newer Apps usually tend to want to have the latest & greatest.

With Ti.Current - Our company has done only 3 Apps in Alloy (targeting 2 platforms (iOS & Android) X 2 layouts (Mobile & Tablets) and came in handy with Alloy - such use cases, I opt-in for Alloy), however, in general, I prefer Classic Ti, everybody that 'does' Alloy, 'does' Classic Ti, and personally, Alloy is made for things to be easy for such use cases.

On Another note - I've heard @mattapperson mention React Native to be more performant _(end result on device)_ than Titanium; We should probably reverse engineer what the engineers @ React Native have done and take the best ideas implemented and bring those to Titanium (or now it's called AppC SDK). I keep a close watch on how React Native is progressing and it reminds me of Ti 2010; They have a long way to go to fix bugs, (Android is not even out), the community just started to build modules, etc;

Overall, I think Performance improvements is the Key, even more than adding new features of iOS7 or 8 _(except for Apple Watch Integration ;), which I think is nearly done from the last time I checked that Jira ticket)_.

Anyways, thats my 2 cents.

**Comment by mattapperson** [comment]
To be clear, reactnative is faster then ti.current not ti.next.
This is due to their "virtual mobile Dom" needing far fewer bridge calls. This could be implemented in alloy and provide further perf boosts.

**Comment by yozef** [comment]
Speaking of ReactNative's virtual Dom @yomybaby has an interesting repo: https://github.com/yomybaby/VirtualTiExample

**Comment by iotashan** [comment]
So, both React Native and NativeScript are interested in Titanium in one way or another. Interesting.
